In [35]:
import tensorflow as tf

In [38]:
print(tf.add(1,2))
print(tf.add([1,2],[3,4]))
print(tf.square(5))
print(tf.reduce_sum([1,2,3]))

print(tf.square(2) + tf.square(3))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)


In [42]:
x = tf.matmul([[1]],[[2,3]]) #행렬곱
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


In [43]:
#넘파이 배열과 차이점 : 가속기 메모리GPU, TPU 사용 가능, Immutable

In [47]:
import numpy as np

ndarray = np.ones([3,3])

print("텐서플로 연산은 자동으로 넘파이배열을 텐서로 변환")
tensor = tf.multiply(ndarray,42)
print(tensor)

print("그리고 넘파이 연산은 자동적으로 텐서를 넘파이배열로 변환")
print(np.add(tensor,1))

print(".numpy() method는 텐서를 넘파이 배열로 강제 변환")
print(tensor.numpy())

텐서플로 연산은 자동으로 넘파이배열을 텐서로 변환
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
그리고 넘파이 연산은 자동적으로 텐서를 넘파이배열로 변환
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
.numpy() method는 텐서를 넘파이 배열로 강제 변환
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [50]:
#GPU 가속
x = tf.random.uniform([3,3])
print("Is it avialable to use GPU? : "),
print(tf.test.is_gpu_available())

print("Is Tensor located in GPU #0? : "),
print(x.device.endswith('GPU:0'))

Is it avialable to use GPU? : 
False
Is Tensor located in GPU #0? : 
False


In [52]:
import time

def time_matmul(x):
    start = time.time()
    for loop in range(10):
        tf.matmul(x, x)

    result = time.time()-start

    print("10 loops: {:0.2f}ms".format(1000*result))

# CPU에서 강제 실행합니다.
print("On CPU:")
with tf.device("CPU:0"):
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith("CPU:0")
    time_matmul(x)

# GPU #0가 이용가능시 GPU #0에서 강제 실행합니다.
if tf.test.is_gpu_available():
    print("On GPU:")
    with tf.device("GPU:0"): # Or GPU:1 for the 2nd GPU, GPU:2 for the 3rd etc.
        x = tf.random.uniform([1000, 1000])
    assert x.device.endswith("GPU:0")
    time_matmul(x)

On CPU:
10 loops: 73.86ms


In [53]:
#데이터셋 : 모델에 데이터셋을 제공하기 위한 파이프라인
#tf.data.Dataset

#소스 데이터셋 생성

In [55]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

# CSV 파일을 생성합니다.
import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
    f.write("""Line 1
Line 2
Line 3
  """)

ds_file = tf.data.TextLineDataset(filename)

In [56]:
ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)

ds_file = ds_file.batch(2)

In [58]:
print('ds_tensors 요소:')
for x in ds_tensors:
    print(x)

print('\nds_file 요소:')
for x in ds_file:
    print(x)

ds_tensors 요소:
tf.Tensor([4 9], shape=(2,), dtype=int32)
tf.Tensor([16 25], shape=(2,), dtype=int32)
tf.Tensor([ 1 36], shape=(2,), dtype=int32)

ds_file 요소:
tf.Tensor([b'Line 1' b'Line 2'], shape=(2,), dtype=string)
tf.Tensor([b'Line 3' b'  '], shape=(2,), dtype=string)
