In [6]:
import tensorflow as tf
from tensorflow import keras

In [8]:
layer = tf.keras.layers.Dense(100)
layer = tf.keras.layers.Dense(10, input_shape = (None,5))

In [11]:
layer(tf.zeros([10,5]))

<tf.Tensor: id=44, shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [14]:
layer.variables #층 안에 있는 모든 변수 확인

[<tf.Variable 'dense_3/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.16880196, -0.38340312, -0.578185  ,  0.16551656,  0.37793416,
          0.60704273,  0.4965536 ,  0.4418872 , -0.08378357, -0.26956153],
        [ 0.22863418, -0.606331  ,  0.34585965,  0.40218705, -0.18036824,
          0.22829902, -0.14934641, -0.39265147,  0.6192238 ,  0.6141152 ],
        [ 0.3680387 , -0.26308423,  0.55735093,  0.46650952, -0.50442046,
          0.36120892, -0.5123651 ,  0.22539842,  0.1785636 , -0.00734282],
        [-0.32545954,  0.24403596,  0.394188  , -0.47530472, -0.05346352,
          0.2138781 , -0.54837745,  0.18970406, -0.3372686 , -0.39867806],
        [-0.5667181 , -0.6306633 , -0.3756245 , -0.13353133, -0.5392212 ,
         -0.09630257, -0.4445932 ,  0.24392891, -0.15110323, -0.15222919]],
       dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [15]:
#또한 변수는 객체의 속성을 통해 편리하게 접근 가능
layer.kernel, layer.bias

(<tf.Variable 'dense_3/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.16880196, -0.38340312, -0.578185  ,  0.16551656,  0.37793416,
          0.60704273,  0.4965536 ,  0.4418872 , -0.08378357, -0.26956153],
        [ 0.22863418, -0.606331  ,  0.34585965,  0.40218705, -0.18036824,
          0.22829902, -0.14934641, -0.39265147,  0.6192238 ,  0.6141152 ],
        [ 0.3680387 , -0.26308423,  0.55735093,  0.46650952, -0.50442046,
          0.36120892, -0.5123651 ,  0.22539842,  0.1785636 , -0.00734282],
        [-0.32545954,  0.24403596,  0.394188  , -0.47530472, -0.05346352,
          0.2138781 , -0.54837745,  0.18970406, -0.3372686 , -0.39867806],
        [-0.5667181 , -0.6306633 , -0.3756245 , -0.13353133, -0.5392212 ,
         -0.09630257, -0.4445932 ,  0.24392891, -0.15110323, -0.15222919]],
       dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

In [16]:
layer.bias

<tf.Variable 'dense_3/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [ ]:
#사용자 정의 층 구현# 중요!!!
#가장 좋은 방법은 tf.keras.Layer클래스 상속 후 다음과 같이 구현
#__init__에서 층이 필요한 매개변수 입력
#build, 입력 텐서의 크기 얻고 남은 초기화 진행
#call, 정방향 연산 진행할 수 있다.

In [22]:
class MyDenseLayer(tf.keras.layers.Layer):
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__() 
        #super(): 상속받은 부모 클래스
        self.num_outputs = num_outputs

    def build(self, input_shape):
        #입력 텐서의 크기를 얻고 남은 초기화 진행 가능
        self.kernel = self.add_variable("kernel",
                                    shape=[int(input_shape[-1]),
                                           self.num_outputs])

    def call(self, input):
        #정방향 연산 가능
        return tf.matmul(input, self.kernel)

layer = MyDenseLayer(10)
print(layer(tf.zeros([10, 5])))
print(layer.trainable_variables)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)
[<tf.Variable 'my_dense_layer_4/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[ 0.32642323,  0.5901906 ,  0.20951986,  0.5681234 , -0.58893627,
         0.52660626, -0.31966788,  0.62273043,  0.57352287, -0.3970539 ],
       [-0.562642  , -0.13942733, -0.48375452,  0.5489121 , -0.2175827 ,
        -0.17729741,  0.41210133, -0.2463302 ,  0.37462705,  0.5758856 ],
       [-0.09389699,  0.60588306,  0.43968982,  0.5084967 ,  0.60889965,
         0.04758316, -0.39692906,  0.46343917,  0.32018477, -0.5654679 ],
       [ 0.05576545, -0.00429022,  0.02835757, -0.15090194, -0.60814816,
        -0.2103762 ,  0.4571702 , 

In [23]:
#모델 : 층 구성
#ML에서 대부분 기존의 층을 조합하여 구현된다.

In [25]:
#다른 층을 포함한 모델을 만들기 위해 사용하는 메인 클래스는 tf.keras.Model
class ResnetIdentityBlock(tf.keras.Model):
    def __init__(self, kernel_size, filters):
        super(ResnetIdentityBlock, self).__init__(name = '')
        filters1, filters2, filters3 = filters
        
        self.conv2a = tf.keras.layers.Conv2D(filters1, (1,1))
        self.bn2a = tf.keras.layers.BatchNormalization()
        
        self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding = 'same')
        self.bn2b = tf.keras.layers.BatchNormalization()
        
        self.conv2c = tf.keras.layers.Conv2D(filters3, (1,1))
        self.bn2c = tf.keras.layers.BatchNormalization()
        
    def call(self, input_tensor, training = False):
        x = self.conv2a(input_tensor)
        x = self.bn2a(x, training = training)
        x = tf.nn.relu(x)
        
        x = self.conv2b(input_tensor)
        x = self.bn2b(x, training = training)
        x = tf.nn.relu(x)
        
        x = self.conv2c(input_tensor)
        x = self.bn2c(x, training = training)
        
        x += input_tensor
        return tf.nn.relu(x)
    
    
block = ResnetIdentityBlock(1, [1,2,3])
print(block(tf.zeros([1,2,3,3])))
print([x.name for x in block.trainable_variables])

tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 2, 3, 3), dtype=float32)
['resnet_identity_block_1/conv2d_3/kernel:0', 'resnet_identity_block_1/conv2d_3/bias:0', 'resnet_identity_block_1/batch_normalization_v2_3/gamma:0', 'resnet_identity_block_1/batch_normalization_v2_3/beta:0', 'resnet_identity_block_1/conv2d_4/kernel:0', 'resnet_identity_block_1/conv2d_4/bias:0', 'resnet_identity_block_1/batch_normalization_v2_4/gamma:0', 'resnet_identity_block_1/batch_normalization_v2_4/beta:0', 'resnet_identity_block_1/conv2d_5/kernel:0', 'resnet_identity_block_1/conv2d_5/bias:0', 'resnet_identity_block_1/batch_normalization_v2_5/gamma:0', 'resnet_identity_block_1/batch_normalization_v2_5/beta:0']


In [26]:
#하지만 대부분 많은 경우에 단순하게 순서대로 층을 쌓아서 하나씩 호출 tf.keras.Sequential

In [29]:
my_seq = tf.keras.Sequential([tf.keras.layers.Conv2D(1,(1,1),
                                                     input_shape = (
                                                     None, None, 3)),
                            tf.keras.layers.BatchNormalization(),
                            tf.keras.layers.Conv2D(2,1,
                                                  padding = 'same'),
                            tf.keras.layers.BatchNormalization(),
                            tf.keras.layers.Conv2D(3,(1,1)),
                            tf.keras.layers.BatchNormalization()])
my_seq(tf.zeros([1,2,3,3]))

<tf.Tensor: id=1437, shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>