In [4]:
A = np.diag([1,2,3])
A

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [5]:
B = np.diag([1,1 / 2, 1 / 3])
B

array([[1.        , 0.        , 0.        ],
       [0.        , 0.5       , 0.        ],
       [0.        , 0.        , 0.33333333]])

In [6]:
A @ B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
A = np.array([[1,1],[1,1]])
np.linalg.det(A)

0.0

In [12]:
A = np.array([[1,1],[1,0]])
B = np.array([[0,1],[1,-1]])
A @ B

array([[1, 0],
       [0, 1]])

In [13]:
B @ A

array([[1, 0],
       [0, 1]])

In [1]:
import numpy as np

A = np.array([[1,1,0],[0,1,1],[1,1,1]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [2]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [3]:
b = np.array([[2],[3],[4]])
b

array([[2],
       [3],
       [4]])

In [4]:
x = Ainv @ b
x

array([[1.],
       [1.],
       [2.]])

In [5]:
A @ x - b

array([[0.],
       [0.],
       [0.]])

In [6]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

array([[1.],
       [1.],
       [2.]])

In [7]:
resid

array([], dtype=float64)

In [8]:
rank

3

In [9]:
s

array([2.41421356, 1.        , 0.41421356])

In [29]:
#연습 문제 2.4.5
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
A = X[:4, [0, 4, 5, 6]]  # 'CRIM', 'NOX', 'RM', 'AGE'
b = y[:4]

In [30]:
A

array([[6.320e-03, 5.380e-01, 6.575e+00, 6.520e+01],
       [2.731e-02, 4.690e-01, 6.421e+00, 7.890e+01],
       [2.729e-02, 4.690e-01, 7.185e+00, 6.110e+01],
       [3.237e-02, 4.580e-01, 6.998e+00, 4.580e+01]])

In [31]:
b

array([24. , 21.6, 34.7, 33.4])

In [32]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])

In [33]:
Ainv = np.linalg.inv(A)
Ainv

array([[-2.35172493e+01,  4.95752613e+01, -9.28388535e+01,
         7.19277399e+01],
       [ 5.96138349e+00,  6.66097478e+00, -2.68388003e+01,
         1.58431788e+01],
       [-2.19803095e-01, -8.06127089e-01,  1.99308607e+00,
        -9.57270077e-01],
       [-9.40782133e-03,  2.15240112e-02,  2.94704793e-02,
        -4.11681401e-02]])

In [34]:
Ainv @ b

array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])

In [37]:
A = np.array([[1,1,0],[0,1,1],[1,1,1],[1,1,2]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [38]:
b = np.array([[2],[2],[3],[4.1]])
b

array([[2. ],
       [2. ],
       [3. ],
       [4.1]])

In [39]:
Apinv = np.linalg.inv(A.T @ A) @ A.T
Apinv

array([[ 0.33333333, -1.        ,  0.33333333,  0.33333333],
       [ 0.5       ,  1.        ,  0.        , -0.5       ],
       [-0.5       ,  0.        ,  0.        ,  0.5       ]])

In [40]:
x = Apinv @ b
x

array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [41]:
A @ x

array([[1.98333333],
       [2.        ],
       [3.03333333],
       [4.08333333]])

In [42]:
b

array([[2. ],
       [2. ],
       [3. ],
       [4.1]])

In [43]:
x, resid, rank, s = np.linalg.lstsq(A ,b)
x

array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [44]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target

In [46]:
# w = X+ b
Xpinv = np.linalg.inv(X.T @ X) @ X.T
Xpinv @ y

array([-9.28965170e-02,  4.87149552e-02, -4.05997958e-03,  2.85399882e+00,
       -2.86843637e+00,  5.92814778e+00, -7.26933458e-03, -9.68514157e-01,
        1.71151128e-01, -9.39621540e-03, -3.92190926e-01,  1.49056102e-02,
       -4.16304471e-01])

In [47]:
x, resid, rank, s = np.linalg.lstsq(X ,y)
x

array([-9.28965170e-02,  4.87149552e-02, -4.05997958e-03,  2.85399882e+00,
       -2.86843637e+00,  5.92814778e+00, -7.26933458e-03, -9.68514157e-01,
        1.71151128e-01, -9.39621540e-03, -3.92190926e-01,  1.49056102e-02,
       -4.16304471e-01])