In [2]:
A = np.array([[1,-2],[2,-3]])
w1, V1 = np.linalg.eig(A)

print(w1)
print(V1)

[-0.99999998 -1.00000002]
[[0.70710678 0.70710678]
 [0.70710678 0.70710678]]


In [3]:
C = np.array([[0,-1],[1,0]])
w3, V3 = np.linalg.eig(C)

print(w3)
print(V3)

[0.+1.j 0.-1.j]
[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]


In [4]:
E = np.array([[2,3],[2,1]])
e1, E1 = np.linalg.eig(E)

print(e1)
print(E1)

[ 4. -1.]
[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


In [5]:
F = np.array([[1,1],[0,1]])
f1, F1 = np.linalg.eig(F)

print(f1)
print(F1)

[1. 1.]
[[ 1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16]]


In [7]:
B = np.array([[2, 3], [2, 1]])
w2, V2 = np.linalg.eig(B)

print(w2)
print(V2)

[ 4. -1.]
[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


In [8]:
V2

array([[ 0.83205029, -0.70710678],
       [ 0.5547002 ,  0.70710678]])

In [9]:
V2_inv = np.linalg.inv(V2)

In [10]:
V2 @ np.diag(w2) @ V2_inv

array([[2., 3.],
       [2., 1.]])

In [12]:
A = np.array([[2,3],[2,1]])
a1, A1 = np.linalg.eig(A)

print(a1)
print(A1)

[ 4. -1.]
[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


In [13]:
A1_inv = np.linalg.inv(A1)

In [15]:
A1 @ np.diag(a1) @ A1_inv

array([[2., 3.],
       [2., 1.]])

In [20]:
B = np.array([[1,1],[0,1]])
b1, B1 = np.linalg.eig(B)
B1_inv = np.linalg.inv(B1)
print(b1)
print(B1)
print(B1_inv)

[1. 1.]
[[ 1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16]]
[[1.00000000e+00 4.50359963e+15]
 [0.00000000e+00 4.50359963e+15]]


In [18]:
B1 @ np.diag(b1) @ B1_inv

array([[1., 0.],
       [0., 1.]])

In [19]:
B1_inv

array([[1.00000000e+00, 4.50359963e+15],
       [0.00000000e+00, 4.50359963e+15]])

In [25]:
d = np.diag([3,3,3])
d
s = np.linalg.inv(d)
s

array([[0.33333333, 0.        , 0.        ],
       [0.        , 0.33333333, 0.        ],
       [0.        , 0.        , 0.33333333]])

In [26]:
#연습 문제 3.3.8
A = np.array([[2,3],[2,1]])
a1, x1 = np.linalg.eig(A)
print(a1)
print(x1)

[ 4. -1.]
[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


In [28]:
x1_inv = np.linalg.inv(x1)
X = x1 @ np.diag(a1) @ x1_inv
X

array([[2., 3.],
       [2., 1.]])

In [38]:
A = np.array([[60,30,20],[30,20,15],[20,15,12]])

w, V = np.linalg.eig(A)
#w는 고윳값, V는 고유벡터
w1, w2, w3 = w
v1 = V[:,0:1] #고유벡터 행렬의 각각의 고유벡터(열벡터)
v2 = V[:,1:2]
v3 = V[:,2:3]
A1 = v1 @ v1.T #랭크-1 행렬 표현
A2 = v2 @ v2.T
A3 = v3 @ v3.T

In [34]:
w

array([84.49913563,  7.33962395,  0.16124042])

In [35]:
V

array([[ 0.82704493,  0.54744843,  0.12765933],
       [ 0.4598639 , -0.52829024, -0.71374689],
       [ 0.32329844, -0.64900666,  0.68867153]])

In [40]:
w1 * A1 + w2 * A2 + w3 * A3

array([[60., 30., 20.],
       [30., 20., 15.],
       [20., 15., 12.]])

In [41]:
np.linalg.inv(A)

array([[ 0.15, -0.6 ,  0.5 ],
       [-0.6 ,  3.2 , -3.  ],
       [ 0.5 , -3.  ,  3.  ]])

In [42]:
1 / w1 * A1 + 1 / w2 * A2 + 1/ w3 * A3

array([[ 0.15, -0.6 ,  0.5 ],
       [-0.6 ,  3.2 , -3.  ],
       [ 0.5 , -3.  ,  3.  ]])

In [43]:
from sklearn.datasets import load_iris
X = load_iris().data

In [44]:
from sklearn.datasets import load_boston
Y = load_boston().data

In [48]:
X_scatter = X.T @ X
X_scatter

array([[5223.85, 2673.43, 3483.76, 1128.14],
       [2673.43, 1430.4 , 1674.3 ,  531.89],
       [3483.76, 1674.3 , 2582.71,  869.11],
       [1128.14,  531.89,  869.11,  302.33]])

In [49]:
x1, y1 = np.linalg.eig(X_scatter)
x1

array([9.20830507e+03, 3.15454317e+02, 1.19780429e+01, 3.55257020e+00])

In [50]:
Y_scatter = Y.T @ Y
x2, y2 = np.linalg.eig(Y_scatter)
x2

array([1.58386796e+08, 1.18747372e+07, 4.17002244e+05, 1.61644573e+05,
       2.52697480e+04, 1.47629635e+04, 8.18396001e+03, 6.07326738e+03,
       4.23577535e+03, 6.06399504e+02, 3.27412564e+02, 3.04157837e+01,
       2.19326965e+00])