In [4]:
import numpy as np

A = (np.arange(9) -4).reshape((3,3))
A

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [11]:
np.linalg.norm(A) ** 2

60.00000000000001

In [17]:
a = np.array([[-4],[-1],[2]])
b = np.array([[-3],[0],[3]])
c = np.array([[2],[1],[4]])

In [18]:
a.T @ a + b.T @ b + c.T @ c

array([[60]])

In [19]:
np.trace(np.eye(3))

3.0

In [26]:
x = np.arange(2).reshape(2,1)
A = (np.arange(4) + 1).reshape(2,2)
np.trace(x.T @ A @ x)

4

In [27]:
np.trace(A @ x @ x.T)

4

In [31]:
A = (np.arange(4) -  2).reshape(2,2)
np.linalg.norm(A) ** 2

5.999999999999999

In [33]:
B = A.T @ A
np.trace(B)

6

In [37]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
a = np.linalg.det(A)

In [38]:
b = np.linalg.det(A.T)

In [40]:
a + b

-9.51619735392994e-16

In [41]:
#연습 문제 2.3.7
A = np.array([[2, -1, 0],[-1,2,-1],[0,-1,2]])
A

array([[ 2, -1,  0],
       [-1,  2, -1],
       [ 0, -1,  2]])

In [75]:
x = (np.arange(2) - 2).reshape(2,1)
x

array([[-2],
       [-1]])

In [58]:
x.T @ A @ x

array([[36]])

In [63]:
np.trace(A)

6

In [64]:
np.linalg.det(A)

4.0

In [67]:
B = (np.arange(4) + 1).reshape(2,2)
B

array([[1, 2],
       [3, 4]])

In [76]:
x.T @ B @ x

array([[18]])

In [77]:
np.trace(B)

5

In [78]:
np.linalg.det(B)

-2.0000000000000004