In [1]:
#리스트 : 많은 숫자 데이터를 하나의 변수에 넣고 관리 -> 속도느리고 메모리 많이 차지
#배열 : 적은 메모리, 빠른 데이터 처리
#둘의 차이점 : 1. 모든 원소가 같은 자료형이어야 한다. 2. 원소의 갯수를 바꿀 수 없다.

In [2]:
#NumPy package import
import numpy as np

In [4]:
#1차원 배열 만들기
ar = np.array([0, 1, 2, 3, 4, 5, 6 ,7 ,8 ,9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(ar)
#리스트와 비슷하지만 자료형은 ndarray

numpy.ndarray

In [7]:
#벡터화 연산 : 배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
answer =[]
for di in data:
    answer.append(2 * di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [10]:
#벡터화 연산을 사용한다면?
x = np.array(data)
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
#참고사항
L = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(2 * L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [12]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
2 * a + b

array([12, 24, 36])

In [16]:
a == 2

array([False,  True, False])

In [19]:
b > 10

array([False,  True,  True])

In [20]:
(a == 2) & (b > 10)

array([False,  True, False])

In [22]:
#2차원 배열 만들기 : 2-dimensional array 행렬matrix 행row 열column
c = np.array([[0, 1, 2], [3, 4, 5]]) # 2 X 3 array using "lists of list"
c

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
#행의 갯수
len(c)

2

In [24]:
#열의 갯수
len(c[0])

3

In [28]:
#연습 문제 4.1.1
d = np.array([[10, 20, 30, 40], [50, 60, 70, 80]]) # 2 X 4 array
d

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [40]:
#3차원 배열 만들기 list of list of list
e = np.array([[[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]],
             [[11,12,13,14],
             [15,16,17,18],
             [19,20,21,22]]]) # 2 X 3 X 4 array
#행, 열, 깊이
len(e), len(e[0]), len(e[0][0])

(2, 3, 4)

In [32]:
#배열의 차원과 크기 알아내기
##ndim : 배열의 차원, shape : 배열의 크기 반환
a = np.array([1,2,3])
print(a.ndim)
print(a.shape)

1
(3,)


In [33]:
c = np.array([[0,1,2],[3,4,5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [45]:
#배열의 인덱싱
a = np.array([0,1,2,3,4])
a[2]

2

In [46]:
a[-1]

4

In [47]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
a[0,0]

0

In [49]:
a[0,1]

1

In [50]:
a[-1,-1] #마지막 행의 마지막 열

5

In [51]:
#배열 슬라이싱
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [52]:
a[0,:]

array([0, 1, 2, 3])

In [53]:
a[:,1] #2번째 열 전체

array([1, 5])

In [55]:
a[1,1:]

array([5, 6, 7])

In [61]:
a[:2,:2] #끝 범위는 포함시키지 않음

array([[0, 1],
       [4, 5]])

In [62]:
#연습문제 4.1.2
m = np.array([[0, 1, 2, 3, 4],
             [5, 6, 7, 8, 9],
             [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [63]:
#1. 값 7 인덱싱
m[1,2]

7

In [67]:
#2. 값 14 인덱싱
m[2,4]

14

In [69]:
#3. 배열[6,7] 슬라이싱
m[1,1:3]

array([6, 7])

In [70]:
#4. 배열 [7,12] 슬라이싱
m[1:,2]

array([ 7, 12])

In [71]:
#5. 배열 [[3,4,],[8,9]] 슬라이싱
m[:2,3:]

array([[3, 4],
       [8, 9]])

In [87]:
#배열 인덱싱(called also by fancy indexing), 실은 질의Querry 기능 수행
# 1. 불리안Boolean배열 방식(인덱스 크기가 원 ndarray크기와 같아야 함)
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [80]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [81]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [82]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [83]:
# 2. 정수 배열 인덱싱
#1차원 배열에서 홀수번째 원소 인덱싱
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [84]:
#배열 크기가 달라도 상관 없음
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [88]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [91]:
a[[2,1,0],:] # 2row>0row,1row>1row, 0row>2row 이동

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [102]:
#연습 문제 4.1.3
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14
              ,15,16,17,18,19,20])
#3의 배수를 찾아라
idx = [2,5,8,11,14,17]
x[idx]

array([ 3,  6,  9, 12, 15, 18])

In [101]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [103]:
#4로 나누면 1이 남는 수를 찾아라
x[x % 4 ==1]

array([ 1,  5,  9, 13, 17])

In [104]:
#3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])