In [13]:
#시드 설정하기 :  시작숫자 = 시드seed
np.random.seed(0) #인수는 0과 같거나 큰 정수

In [14]:
np.random.rand(5) #0과 1사이 난수 생성

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [15]:
#데이터의 순서 바꾸기 : shuffle
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.random.shuffle(x)
x

array([0, 8, 7, 9, 1, 3, 5, 2, 4, 6])

In [18]:
#데이터 샘플링 : choice
#numpy.random.choice(a, size=None, replace=True, p=None)
#a : 배열이면 원래 데이터, 정수면 arange(a) 명령으로 데이터 생성
#size : 정수, 샘플 숫자
#replace : 불리언, True이면 한번 선택한 데이터 다시 선택 가능
#p : 배열, 각 데이터가 선택될 수 있는 확률

In [23]:
np.random.choice(5,5,replace=False) # shuffle 명령과 같다

array([1, 4, 2, 3, 0])

In [24]:
np.random.choice(5,3,replace=False)

array([0, 1, 4])

In [27]:
np.random.choice(5,10)

array([2, 2, 0, 1, 1, 1, 1, 3, 3, 2])

In [32]:
np.random.choice(5,10,p=[0.1,0,0.3,0.6,0])

array([2, 2, 2, 2, 3, 0, 3, 3, 2, 3])

In [ ]:
#난수 생성 ## random sub_package
##rand: 0부터 1사이의 균일 분포
##randn: 가우시안 표준 정규 분포
##randint: 균일 분포의 정수 난수

In [35]:
np.random.rand(5,2)

array([[0.57225191, 0.22308163],
       [0.95274901, 0.44712538],
       [0.84640867, 0.69947928],
       [0.29743695, 0.81379782],
       [0.39650574, 0.8811032 ]])

In [37]:
np.random.randn(3,5)

array([[ 1.03081595, -1.27698899,  0.83771977, -1.49011141, -1.070215  ],
       [-0.20912862,  0.60457228, -1.74305823,  1.52422681,  1.86357532],
       [ 1.29137792,  1.30069627,  0.91820283, -0.15880047, -0.96406336]])

In [40]:
##randint: 균일 분포의 정수 난수
#numpy.random.randint(low, high=None, size=None)
##high없으면 0과 low사이, high있으면 low와 high사이, size는 난수의 숫자
np.random.randint(10,size=10)

array([2, 1, 4, 2, 5, 5, 5, 2, 5, 7])

In [41]:
np.random.randint(10,20,size=10)

array([17, 16, 11, 16, 17, 12, 13, 11, 19, 15])

In [42]:
np.random.randint(10,20,size=(3,4))

array([[19, 19, 12, 10],
       [19, 11, 19, 10],
       [16, 10, 14, 18]])

In [43]:
#정수 데이터 카운팅
##실수값 > 히스토그램 등으로 분석
##정수값 > unique, bincount 명령(NumPy)
##unique : 데이터에서 중복된 값 제외하고 출력
np.unique([11,11,2,2,34,34])
##return_counts 인수 True 설정시 각 값을 가진 데이터 갯수 출력

array([ 2, 11, 34])

In [44]:
a = np.array(['a','b','b','c','a'])
index, count = np.unique(a, return_counts=True)

In [45]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [46]:
count

array([2, 2, 1], dtype=int64)

In [51]:
#bincount : 특정 범위안의 수에 대해 0인 경우까지 고려
np.bincount([1,1,2,2,2,3],minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)