In [11]:
#벡터화 연산
import numpy as np
x = np.arange(1, 10001)
y = np.arange(10001, 20001)
%time
z = x + y
z[:10]

Wall time: 0 ns


array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [12]:
#논리연산도 벡터화 연산 가능
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
a == b

array([False,  True, False,  True])

In [13]:
a >= b

array([False,  True,  True,  True])

In [18]:
#배열된 모든 원소가 다 같으냐?? all
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])
np.all(a==b)

False

In [15]:
np.all(a==c)

True

In [19]:
#지수, 로그 함수 등의 수학 함수도 벡터화 연산 가능
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [20]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [21]:
10 ** a

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [22]:
np.log(a + 1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [23]:
#스칼라와 벡터/행력의 곱셈
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [26]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [28]:
#브로드캐스팅Broadcasting
##Broadcasting을 통해 크기 다른 배열도 사칙연산 가능(크기가 작은 배열 자동 반복 확장)
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [30]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [31]:
x + y

array([1, 2, 3, 4, 5])

In [32]:
x + 1

array([1, 2, 3, 4, 5])

In [33]:
#broadcasting은 더 높은 차원에서도 가능
x = np.vstack([range(7)[i:i+3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [34]:
y = np.arange(5)[:,np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [35]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [36]:
y = np.arange(3)
y

array([0, 1, 2])

In [37]:
x + y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [41]:
#차원 축소 연산
##최대/최소: min, max, argmin, argmax
##통계: sum, mean, median, std, var
##불리언: all, any
x = np.arange(4)
x

array([0, 1, 2, 3])

In [42]:
np.sum(x)

6

In [43]:
x.sum()

6

In [46]:
x = np.array([1,3,2])
x.min()

1

In [47]:
x.max()

3

In [48]:
x.argmin() # 최소값의 위치arguments of min

0

In [49]:
x.argmax()

1

In [68]:
x = np.array([1,2,3,1])
x.mean()

1.75

In [51]:
np.median(x) #중앙값 (1,2,3,1)->(1,1,2,3)의 literally 가운데 있는 값

1.5

In [52]:
np.all([True,True,False])

False

In [2]:
np.any([True, True, False])

True

In [71]:
a = np.zeros((100,100), dtype=np.int)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [72]:
np.any(a != 0)

False

In [73]:
np.all(a == a)

True

In [74]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a<=b)&(b<=c)).all()

True

In [3]:
#연산의 대상이 2차원 이상인 경우
##axis=0>열 연산(default),axis=1>행 연산
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [5]:
x.sum()

6

In [6]:
x.sum(axis=0) # 열 연산

array([3, 3])

In [7]:
x.sum(axis=1) # 행 연산

array([2, 4])

In [19]:
#연습 문제 4.1.5
a = np.arange(6)
b = np.tile(a,(5,1))
b

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [21]:
#전체의 최댓값
b.max()

5

In [22]:
#각 행의 합
b.sum(axis = 1)

array([15, 15, 15, 15, 15])

In [23]:
#각 열의 평균
b.mean(axis=0)

array([0., 1., 2., 3., 4., 5.])

In [25]:
#정렬 : sort 명령 또는 method를 이용해 배열 안의 원소를 크기에 따라 정렬
##axis를 이용해 axis=0>각열따로,axis=1>각행따로,default=-1
a = np.array([[4,3,5,7],
             [1,12,11,9],
             [2,15,1,14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [26]:
np.sort(a) # axis=-1 or axis=1과 동일

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [27]:
np.sort(a,axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [29]:
a.sort(axis=1) 
a # 해당 객체의 자료 자체가 변화하는 in-place method

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [38]:
#자료를 정렬하는 것이 아니라 순서만 알고 싶다면 argsort
a = np.array([42,38,12,25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [39]:
a[j]

array([12, 25, 38, 42])

In [40]:
np.sort(a)

array([12, 25, 38, 42])

In [70]:
#연습 문제 4.1.6
a = np.array([1,2,3,4])
b = np.array([46,99,100,71])
c = np.array([81,59,90,100])
d = np.argsort(b)
d

array([0, 3, 1, 2], dtype=int64)

In [71]:
a[d]

array([1, 4, 2, 3])

In [72]:
b[d]

array([ 46,  71,  99, 100])

In [73]:
c[d]

array([ 81, 100,  59,  90])

In [74]:
np.stack([a[d],b[d],c[d]])

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])